import { contractService } from '$lib/contractService.js';
class PriceDisplayService { constructor(){ this.prices=new Map(); this.priceUpdateInterval=null; this.subscribers=new Set(); this.updateInterval=30000; this.isInitialized=false; }
  async initialize(){ try { await contractService.initialize(); this.isInitialized=true; this.startPriceUpdates(); return true; } catch(e){ console.error('Failed to initialize price display service:', e); throw e; } }
  startPriceUpdates(){ if(this.priceUpdateInterval) clearInterval(this.priceUpdateInterval); this.priceUpdateInterval=setInterval(()=> this.updateAllPrices(), this.updateInterval); this.updateAllPrices(); }
  stopPriceUpdates(){ if(this.priceUpdateInterval){ clearInterval(this.priceUpdateInterval); this.priceUpdateInterval=null; } }
  async updateAllPrices(){ if(!this.isInitialized) return; try { const supportedTokens = await contractService.contract.getSupportedTokens(); for(const tokenAddress of supportedTokens){ try { const price = await contractService.contract.getTokenPrice(tokenAddress); const { ethers } = await import('ethers'); const priceInEther = ethers.formatEther(price); const old=this.prices.get(tokenAddress); this.prices.set(tokenAddress,{ current:parseFloat(priceInEther), previous:old?.current||parseFloat(priceInEther), change: old? ((parseFloat(priceInEther)-old.current)/old.current)*100 : 0, timestamp:Date.now(), address:tokenAddress }); } catch(err){ console.error(`Failed price for ${tokenAddress}:`, err); } } this.notifySubscribers(); } catch(err){ console.error('Failed to update prices:', err); } }
  getPrice(addr){ const d=this.prices.get(addr); return d? { price:d.current, change:d.change, timestamp:d.timestamp }:null; }
  getAllPrices(){ const res={}; this.prices.forEach((d,a)=>{ res[a]={ price:d.current, change:d.change, timestamp:d.timestamp }; }); return res; }
  async getTokenInfo(addr){ if(!this.isInitialized) return null; try { const info = await contractService.contract.getTokenInfo(addr); return { symbol:info.symbol, decimals:info.decimals, isSupported:info.isSupported, category:info.category, address:addr }; } catch(e){ console.error('Failed token info:', e); return null; } }
  async getHistoricalData(addr,timeframe='1d'){ const current=this.getPrice(addr); if(!current) return []; const now=Date.now(); const intervals={ '1h':{count:60, interval:60*1000}, '1d':{count:24, interval:60*60*1000}, '7d':{count:7*24, interval:60*60*1000}, '30d':{count:30, interval:24*60*60*1000} }; const { count, interval } = intervals[timeframe]||intervals['1d']; let price=current.price*(0.95+Math.random()*0.1); const data=[]; for(let i=count;i>=0;i--){ const ts=now - i*interval; const change=(Math.random()-0.5)*0.02; price=price*(1+change); data.push({ timestamp:ts, price:Number(price.toFixed(6)) }); } if(data.length) data[data.length-1].price=current.price; return data; }
  subscribe(cb){ this.subscribers.add(cb); return ()=> this.subscribers.delete(cb); }
  notifySubscribers(){ const all=this.getAllPrices(); this.subscribers.forEach(cb=>{ try { cb(all);} catch(e){ console.error('Subscriber error:', e);} }); }
  formatPrice(price,decimals=6){ if(price==null || isNaN(price)) return '--'; if(price>=1000) return new Intl.NumberFormat('en-US',{ style:'currency', currency:'USD', minimumFractionDigits:2, maximumFractionDigits:2 }).format(price); return new Intl.NumberFormat('en-US',{ style:'currency', currency:'USD', minimumFractionDigits:decimals, maximumFractionDigits:decimals }).format(price); }
  formatPriceChange(change){ if(change==null || isNaN(change)) return '--'; const sign=change>=0?'+':''; return `${sign}${change.toFixed(2)}%`; }
  async getTokenSymbol(addr){ const info = await this.getTokenInfo(addr); return info? info.symbol : 'UNKNOWN'; }
  destroy(){ this.stopPriceUpdates(); this.subscribers.clear(); this.prices.clear(); this.isInitialized=false; }
}
export const priceDisplayService = new PriceDisplayService();
export default priceDisplayService;