<script>
	import { onMount } from 'svelte';
	import { walletAddress, walletBalance } from '$lib/stores/wallet.js';
	import PriceChart from '$lib/components/PriceChart.svelte';
	import PortfolioOverview from '$lib/components/PortfolioOverview.svelte';
	import ActiveSettings from '$lib/components/ActiveSettings.svelte';
	import QuickActions from '$lib/components/QuickActions.svelte';
	import EventsMonitor from '$lib/EventsMonitor.svelte';
	import StrategyDrawer from '$lib/components/StrategyDrawer.svelte';
	let selectedToken=null; let portfolioValue=125487.32; let portfolioChange=5.67; let totalAssets=8; let timeframe='1d';
	const STORAGE_KEY='reactive.dashboard.v1';
	const TIMEFRAME_LABELS=[ {key:'1h',label:'1H'},{key:'1d',label:'24H'},{key:'7d',label:'7D'},{key:'30d',label:'30D'} ];
	onMount(async()=>{ try { if(typeof localStorage!=='undefined'){ const raw=localStorage.getItem(STORAGE_KEY); if(raw){ const parsed=JSON.parse(raw); if(parsed?.timeframe && ['1h','1d','7d','30d'].includes(parsed.timeframe)) timeframe=parsed.timeframe; if(parsed?.token?.symbol) selectedToken=parsed.token; } } } catch(e){ console.warn('Persisted dashboard state load failed', e);} const wallet=$walletAddress; if(wallet && window.ethereum){ try { const { priceDisplayService } = await import('$lib/priceDisplayService.js'); await priceDisplayService.initialize(); } catch(e){ console.error('Failed to initialize price display service:', e); } } const handleTokenSelection = e => { selectedToken = e.detail; }; window.addEventListener('tokenSelected', handleTokenSelection); if(!selectedToken){ selectedToken={ symbol:'ETH', name:'Ethereum', address:'0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2', price:2587.45, change:2.34 }; } return ()=> window.removeEventListener('tokenSelected', handleTokenSelection); });
		$: (async()=>{ try { if(typeof localStorage!=='undefined'){ localStorage.setItem(STORAGE_KEY, JSON.stringify({ timeframe, token: selectedToken && { symbol:selectedToken.symbol, name:selectedToken.name, address:selectedToken.address, price:selectedToken.price, change:selectedToken.change } })); } } catch { /* ignore persistence errors */ } })();
</script>
<svelte:head><title>Dashboard - Reactive Portfolio Manager</title></svelte:head>
<div class="space-y-6" role="main" aria-label="Dashboard">
	<div class="bg-gradient-to-r from-blue-600 to-purple-600 rounded-lg p-6 text-white"><div class="flex items-center justify-between"><div><h1 class="text-2xl font-bold mb-2">Welcome to Reactive Portfolio</h1><p class="text-blue-100">Address: <span class="font-mono">{$walletAddress}</span></p></div><div class="text-right"><div class="text-3xl font-bold">${portfolioValue.toLocaleString()}</div><div class="flex items-center justify-end mt-1"><span class="text-sm">Portfolio Value</span><span class="ml-2 text-sm font-medium" class:text-green-300={portfolioChange>=0} class:text-red-300={portfolioChange<0}>{portfolioChange>=0?'+':''}{portfolioChange}%</span></div></div></div></div>
	<div class="grid grid-cols-1 md:grid-cols-3 gap-6">
		<div class="bg-white dark:bg-gray-800 rounded-lg p-6 shadow-sm border border-gray-200 dark:border-gray-700"><div class="flex items-center"><div class="w-10 h-10 bg-blue-100 dark:bg-blue-900 rounded-lg flex items-center justify-center"><svg class="w-6 h-6 text-blue-600 dark:text-blue-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1" /></svg></div><div class="ml-4"><p class="text-sm font-medium text-gray-500 dark:text-gray-400">Total Balance</p><p class="text-2xl font-bold text-gray-900 dark:text-white">{$walletBalance ? parseFloat($walletBalance).toFixed(4) : '0'} REACT</p></div></div></div>
		<div class="bg-white dark:bg-gray-800 rounded-lg p-6 shadow-sm border border-gray-200 dark:border-gray-700"><div class="flex items-center"><div class="w-10 h-10 bg-green-100 dark:bg-green-900 rounded-lg flex items-center justify-center"><svg class="w-6 h-6 text-green-600 dark:text-green-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 7h8m0 0v8m0-8l-8 8-4-4-6 6" /></svg></div><div class="ml-4"><p class="text-sm font-medium text-gray-500 dark:text-gray-400">Active Assets</p><p class="text-2xl font-bold text-gray-900 dark:text-white">{totalAssets}</p></div></div></div>
		<div class="bg-white dark:bg-gray-800 rounded-lg p-6 shadow-sm border border-gray-200 dark:border-gray-700"><div class="flex items-center"><div class="w-10 h-10 bg-purple-100 dark:bg-purple-900 rounded-lg flex items-center justify-center"><svg class="w-6 h-6 text-purple-600 dark:text-purple-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" /></svg></div><div class="ml-4"><p class="text-sm font-medium text-gray-500 dark:text-gray-400">24h Change</p><p class="text-2xl font-bold" class:text-green-600={portfolioChange>=0} class:text-red-600={portfolioChange<0}>{portfolioChange>=0?'+':''}{portfolioChange}%</p></div></div></div>
	</div>
	<div class="grid grid-cols-1 xl:grid-cols-3 gap-6">
		<div class="xl:col-span-2"><div class="bg-white dark:bg-gray-800 rounded-lg p-6 shadow-sm border border-gray-200 dark:border-gray-700"><div class="flex items-center justify-between mb-4"><div><h2 class="text-lg font-semibold text-gray-900 dark:text-white">{selectedToken ? `${selectedToken.name} (${selectedToken.symbol})` : 'Select a token'}</h2>{#if selectedToken}<div class="flex items-center mt-1"><span class="text-2xl font-bold text-gray-900 dark:text-white">${selectedToken.price ? selectedToken.price.toFixed(2) : 'Loading...'}</span><span class="ml-2 text-sm font-medium px-2 py-1 rounded-full" class:bg-green-100={selectedToken.change>=0} class:text-green-800={selectedToken.change>=0} class:bg-red-100={selectedToken.change<0} class:text-red-800={selectedToken.change<0}>{selectedToken.change>=0?'+':''}{selectedToken.change}%</span></div>{/if}</div><div class="flex items-center gap-1 rounded-md bg-gray-100 dark:bg-gray-700 p-1" role="radiogroup" aria-label="Timeframe selector">{#each TIMEFRAME_LABELS as tf (tf.key)}<button type="button" on:click={()=> timeframe=tf.key} role="radio" aria-checked={timeframe===tf.key} aria-label={`${tf.label} timeframe`} class="px-3 py-1 text-xs font-medium rounded-md transition-colors focus:outline-none focus-visible:ring-2 focus-visible:ring-blue-500" class:bg-white={timeframe===tf.key} class:text-gray-900={timeframe===tf.key} class:dark:bg-gray-900={timeframe===tf.key} class:dark:text-white={timeframe===tf.key} class:text-gray-500={timeframe!==tf.key} class:hover:text-gray-700={timeframe!==tf.key} class:dark:text-gray-300={timeframe!==tf.key} class:dark:hover:text-gray-100={timeframe!==tf.key}>{tf.label}</button>{/each}</div></div><div class="h-80"><PriceChart {selectedToken} {timeframe} /></div></div></div>
		<div class="space-y-6"><ActiveSettings /><QuickActions /><StrategyDrawer {selectedToken} automationAddress={null} /></div>
	</div>
	<div class="grid grid-cols-1 lg:grid-cols-2 gap-6"><PortfolioOverview /><div class="bg-white dark:bg-gray-800 rounded-lg p-6 shadow-sm border border-gray-200 dark:border-gray-700"><h3 class="text-lg font-semibold text-gray-900 dark:text-white mb-4">Recent Activity</h3><div class="space-y-4"><div class="flex items-center justify-between py-2 border-b border-gray-100 dark:border-gray-700"><div class="flex items-center"><div class="w-8 h-8 bg-green-100 dark:bg-green-900 rounded-full flex items-center justify-center mr-3"><svg class="w-4 h-4 text-green-600 dark:text-green-400" fill="currentColor" viewBox="0 0 20 20"><path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" /></svg></div><div><p class="text-sm font-medium text-gray-900 dark:text-white">Stop-loss Updated</p><p class="text-xs text-gray-500 dark:text-gray-400">Set to 15% for ETH</p></div></div><span class="text-xs text-gray-500 dark:text-gray-400">2 min ago</span></div><div class="flex items-center justify-between py-2 border-b border-gray-100 dark:border-gray-700"><div class="flex items-center"><div class="w-8 h-8 bg-blue-100 dark:bg-blue-900 rounded-full flex items-center justify-center mr-3"><svg class="w-4 h-4 text-blue-600 dark:text-blue-400" fill="currentColor" viewBox="0 0 20 20"><path d="M3 4a1 1 0 011-1h12a1 1 0 011 1v2a1 1 0 01-1 1H4a1 1 0 01-1-1V4zM3 10a1 1 0 011-1h6a1 1 0 011 1v6a1 1 0 01-1 1H4a1 1 0 01-1-1v-6zM14 9a1 1 0 00-1 1v6a1 1 0 001 1h2a1 1 0 001-1v-6a1 1 0 00-1-1h-2z" /></svg></div><div><p class="text-sm font-medium text-gray-900 dark:text-white">Portfolio Rebalanced</p><p class="text-xs text-gray-500 dark:text-gray-400">ETH: 60%, BTC: 40%</p></div></div><span class="text-xs text-gray-500 dark:text-gray-400">1 hour ago</span></div><div class="flex items-center justify-between py-2"><div class="flex items-center"><div class="w-8 h-8 bg-yellow-100 dark:bg-yellow-900 rounded-full flex items-center justify-center mr-3"><svg class="w-4 h-4 text-yellow-600 dark:text-yellow-400" fill="currentColor" viewBox="0 0 20 20"><path fill-rule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clip-rule="evenodd" /></svg></div><div><p class="text-sm font-medium text-gray-900 dark:text-white">Take-profit Set</p><p class="text-xs text-gray-500 dark:text-gray-400">25% for LINK position</p></div></div><span class="text-xs text-gray-500 dark:text-gray-400">3 hours ago</span></div></div></div></div>
	<div class="mt-8"><EventsMonitor maxEvents={10} /></div>
</div>
