services:
  - type: web
    name: reactive-portfolio
    env: node
    region: oregon
    plan: free
    buildCommand: cd client && NODE_OPTIONS="--max-old-space-size=460" pnpm install --no-frozen-lockfile && NODE_OPTIONS="--max-old-space-size=460" pnpm run build
    startCommand: cd client && pnpm run preview
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
      - key: PNPM_VERSION
        value: 9
      - key: NODE_OPTIONS
        value: --max-old-space-size=460
