<script>
  import { onMount } from 'svelte';
  export let open=false;
  const tokens = { altcoins:[{ symbol:'ETH', name:'Ethereum', address:'0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2', price:null, change:null },{ symbol:'ADA', name:'Cardano', address:'0x3EE2200Efb3400fAbB9AacF31297cBdD1d435D47', price:null, change:null },{ symbol:'DOT', name:'Polkadot', address:'0x7083609fCE4d1d8Dc0C979AAb8c869Ea2C873402', price:null, change:null },{ symbol:'LINK', name:'Chainlink', address:'0x514910771AF9Ca656af840dff83E8264EcF986CA', price:null, change:null },{ symbol:'UNI', name:'Uniswap', address:'0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984', price:null, change:null }], memecoins:[{ symbol:'DOGE', name:'Dogecoin', address:'0x4206931337dc273a630d328dA6441786BfaD668f', price:null, change:null }], stablecoins:[{ symbol:'USDC', name:'USD Coin', address:'0xA0b86a33E6441b8FadB9c2FF932293e3dD4ff8cE', price:1, change:0.01 },{ symbol:'USDT', name:'Tether', address:'0xdAC17F958D2ee523a2206206994597C13D831ec7', price:1, change:-0.01 }], btc:[{ symbol:'WBTC', name:'Wrapped Bitcoin', address:'0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599', price:null, change:null }] };
  let selectedToken=null; let query=''; let expandedCategories={ altcoins:true, memecoins:false, stablecoins:false, btc:true };
  function toggleCategory(cat){ expandedCategories[cat]=!expandedCategories[cat]; }
  function selectToken(token){ selectedToken=token; window.dispatchEvent(new CustomEvent('tokenSelected',{ detail:token })); }
  function formatPrice(price){ if(price===null) return 'Loading...'; if(price<0.01) return `$${price.toFixed(6)}`; if(price<1) return `$${price.toFixed(4)}`; return `$${price.toFixed(2)}`; }
  function formatChange(change){ if(change===null) return ''; const sign=change>=0?'+':''; return `${sign}${change.toFixed(2)}%`; }
  function filtered(list){ if(!query.trim()) return list; const q=query.trim().toLowerCase(); return list.filter(t=> t.symbol.toLowerCase().includes(q)|| t.name.toLowerCase().includes(q)); }
  onMount(()=>{ const updatePrices=()=>{ Object.values(tokens).flat().forEach(token=>{ if(!['USDC','USDT','DAI','FRAX'].includes(token.symbol)){ if(token.price===null){ if(token.symbol==='WBTC') token.price=45000+Math.random()*5000; else if(token.symbol==='ETH') token.price=2500+Math.random()*500; else token.price=Math.random()*10+0.1; } const changePercent=(Math.random()-0.5)*10; token.change=changePercent; token.price *= (1+changePercent/100); } }); }; updatePrices(); const interval=setInterval(updatePrices,10000); return ()=> clearInterval(interval); });
</script>
<div class="flex">
  {#if open}<div class="fixed inset-0 z-40 lg:hidden" aria-hidden="true"><div class="fixed inset-0 bg-gray-600 bg-opacity-75" on:click={()=> open=false}></div></div>{/if}
  <div class="fixed inset-y-0 left-0 z-50 w-80 bg-white dark:bg-gray-800 shadow-xl transform transition-transform duration-300 ease-in-out lg:translate-x-0 lg:static lg:inset-0" class:translate-x-0={open} class:-translate-x-full={!open}>
    <div class="flex items-center justify-between h-16 px-4 border-b border-gray-200 dark:border-gray-700"><h2 class="text-lg font-semibold text-gray-900 dark:text-white">Tokens</h2><button on:click={()=> open=false} class="p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 dark:hover:bg-gray-700 lg:hidden"><svg class="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" /></svg></button></div>
    <div class="px-4 py-3 border-b border-gray-200 dark:border-gray-700"><div class="relative"><label for="token-search" class="sr-only">Search tokens</label><input id="token-search" type="text" placeholder="Search tokens..." aria-label="Search tokens" bind:value={query} class="w-full pl-9 pr-3 py-2 text-sm rounded-md bg-gray-50 dark:bg-gray-700 border border-gray-300 dark:border-gray-600 focus:outline-none focus:ring-2 focus:ring-blue-500/60" /><svg class="w-4 h-4 absolute left-2.5 top-2.5 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-4.35-4.35M11 19a8 8 0 100-16 8 8 0 000 16z" /></svg>{#if query}<button type="button" on:click={()=> query=''} class="absolute right-2 top-2 text-gray-400 hover:text-gray-600 dark:hover:text-gray-300"><svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" /></svg></button>{/if}</div></div>
    <div class="flex-1 overflow-y-auto"><nav class="px-4 py-4 space-y-2" role="navigation" aria-label="Token categories">
      <div class="space-y-1"><button on:click={()=> toggleCategory('btc')} class="flex items-center justify-between w-full px-2 py-2 text-sm font-medium text-gray-900 dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 rounded-md"><div class="flex items-center"><div class="w-2 h-2 bg-orange-500 rounded-full mr-3"></div><span>Bitcoin</span></div><svg class="w-4 h-4 transition-transform" class:rotate-90={expandedCategories.btc} fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" /></svg></button>{#if expandedCategories.btc}<div class="ml-4 space-y-1">{#each filtered(tokens.btc) as token (token.symbol)}<button on:click={()=> selectToken(token)} class="flex items-center justify-between w-full px-3 py-2 text-sm text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-md transition-colors" class:bg-blue-50={selectedToken?.symbol===token.symbol} class:dark:bg-blue-900={selectedToken?.symbol===token.symbol} class:text-blue-600={selectedToken?.symbol===token.symbol} class:dark:text-blue-400={selectedToken?.symbol===token.symbol}><div class="flex items-center"><div class="w-8 h-8 bg-orange-500 rounded-full flex items-center justify-center text-xs font-bold text-white mr-3">{token.symbol.slice(0,2)}</div><div class="text-left"><div class="font-medium">{token.symbol}</div><div class="text-xs text-gray-500 dark:text-gray-400">{token.name}</div></div></div><div class="text-right text-xs"><div class="font-medium">{formatPrice(token.price)}</div><div class="text-xs" class:text-green-500={token.change>=0} class:text-red-500={token.change<0}>{formatChange(token.change)}</div></div></button>{/each}</div>{/if}</div>
      <div class="space-y-1"><button on:click={()=> toggleCategory('altcoins')} class="flex items-center justify-between w-full px-2 py-2 text-sm font-medium text-gray-900 dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 rounded-md"><div class="flex items-center"><div class="w-2 h-2 bg-blue-500 rounded-full mr-3"></div><span>Altcoins ({tokens.altcoins.length})</span></div><svg class="w-4 h-4 transition-transform" class:rotate-90={expandedCategories.altcoins} fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" /></svg></button>{#if expandedCategories.altcoins}<div class="ml-4 space-y-1 max-h-64 overflow-y-auto">{#each filtered(tokens.altcoins) as token (token.symbol)}<button on:click={()=> selectToken(token)} class="flex items-center justify-between w-full px-3 py-2 text-sm text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-md transition-colors" class:bg-blue-50={selectedToken?.symbol===token.symbol} class:dark:bg-blue-900={selectedToken?.symbol===token.symbol} class:text-blue-600={selectedToken?.symbol===token.symbol} class:dark:text-blue-400={selectedToken?.symbol===token.symbol}><div class="flex items-center"><div class="w-8 h-8 bg-blue-500 rounded-full flex items-center justify-center text-xs font-bold text-white mr-3">{token.symbol.slice(0,2)}</div><div class="text-left"><div class="font-medium">{token.symbol}</div><div class="text-xs text-gray-500 dark:text-gray-400">{token.name}</div></div></div><div class="text-right text-xs"><div class="font-medium">{formatPrice(token.price)}</div><div class="text-xs" class:text-green-500={token.change>=0} class:text-red-500={token.change<0}>{formatChange(token.change)}</div></div></button>{/each}</div>{/if}</div>
      <div class="space-y-1"><button on:click={()=> toggleCategory('memecoins')} class="flex items-center justify-between w-full px-2 py-2 text-sm font-medium text-gray-900 dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 rounded-md"><div class="flex items-center"><div class="w-2 h-2 bg-purple-500 rounded-full mr-3"></div><span>Memecoins ({tokens.memecoins.length})</span></div><svg class="w-4 h-4 transition-transform" class:rotate-90={expandedCategories.memecoins} fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" /></svg></button>{#if expandedCategories.memecoins}<div class="ml-4 space-y-1 max-h-48 overflow-y-auto">{#each filtered(tokens.memecoins) as token (token.symbol)}<button on:click={()=> selectToken(token)} class="flex items-center justify-between w-full px-3 py-2 text-sm text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-md transition-colors" class:bg-blue-50={selectedToken?.symbol===token.symbol} class:dark:bg-blue-900={selectedToken?.symbol===token.symbol} class:text-blue-600={selectedToken?.symbol===token.symbol} class:dark:text-blue-400={selectedToken?.symbol===token.symbol}><div class="flex items-center"><div class="w-8 h-8 bg-purple-500 rounded-full flex items-center justify-center text-xs font-bold text-white mr-3">{token.symbol.slice(0,2)}</div><div class="text-left"><div class="font-medium">{token.symbol}</div><div class="text-xs text-gray-500 dark:text-gray-400">{token.name}</div></div></div><div class="text-right text-xs"><div class="font-medium">{formatPrice(token.price)}</div><div class="text-xs" class:text-green-500={token.change>=0} class:text-red-500={token.change<0}>{formatChange(token.change)}</div></div></button>{/each}</div>{/if}</div>
      <div class="space-y-1"><button on:click={()=> toggleCategory('stablecoins')} class="flex items-center justify-between w-full px-2 py-2 text-sm font-medium text-gray-900 dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 rounded-md"><div class="flex items-center"><div class="w-2 h-2 bg-green-500 rounded-full mr-3"></div><span>Stablecoins ({tokens.stablecoins.length})</span></div><svg class="w-4 h-4 transition-transform" class:rotate-90={expandedCategories.stablecoins} fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" /></svg></button>{#if expandedCategories.stablecoins}<div class="ml-4 space-y-1">{#each filtered(tokens.stablecoins) as token (token.symbol)}<button on:click={()=> selectToken(token)} class="flex items-center justify-between w-full px-3 py-2 text-sm text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-md transition-colors" class:bg-blue-50={selectedToken?.symbol===token.symbol} class:dark:bg-blue-900={selectedToken?.symbol===token.symbol} class:text-blue-600={selectedToken?.symbol===token.symbol} class:dark:text-blue-400={selectedToken?.symbol===token.symbol}><div class="flex items-center"><div class="w-8 h-8 bg-green-500 rounded-full flex items-center justify-center text-xs font-bold text-white mr-3">{token.symbol.slice(0,2)}</div><div class="text-left"><div class="font-medium">{token.symbol}</div><div class="text-xs text-gray-500 dark:text-gray-400">{token.name}</div></div></div><div class="text-right text-xs"><div class="font-medium">{formatPrice(token.price)}</div><div class="text-xs" class:text-green-500={token.change>=0} class:text-red-500={token.change<0}>{formatChange(token.change)}</div></div></button>{/each}</div>{/if}</div>
    </nav></div>
  </div>
</div>