<script>
  import { onMount } from 'svelte';
  import { automationService } from '$lib/automationService.js';
  import { notify } from '$lib/notify.js';
  import { secureContractService } from '$lib/secureContractService.js';
  import { ethers } from 'ethers';
  export let automationAddress; export let selectedToken = null;
  let account=null; let strategy=null; let loading=false; let form={ stopLossBps:'', takeProfitBps:'', coolDown:300, sellPortionBps:10000, slippageBps:200, enabled:true }; let txStatus=''; let approving=false; let allowance=null; let portfolioAddress=null;
  onMount(async()=>{ try { await secureContractService.initialize(); account = secureContractService.account; if(automationAddress){ await automationService.initialize(automationAddress); } if(secureContractService?.contract){ portfolioAddress = secureContractService.contract.target || secureContractService.contract.address; } hydrate(); } catch(e){ console.error('Strategy init failed', e); } });
  $: if(selectedToken && automationService.initialized && account){ hydrate(); }
  async function hydrate(){ if(!selectedToken?.address || !automationService.initialized || !account) return; try { loading=true; strategy = await automationService.getStrategy(account, selectedToken.address); if(strategy.enabled){ form.stopLossBps = strategy.stopLossBps || ''; form.takeProfitBps = strategy.takeProfitBps || ''; form.coolDown = strategy.coolDown || 300; form.sellPortionBps = strategy.sellPortionBps || 10000; form.slippageBps = strategy.slippageBps || 200; form.enabled = strategy.enabled; } } catch(e){ console.warn('hydrate failed', e.message);} finally { loading=false; } }
  async function save(){ if(!selectedToken?.address) return; try { txStatus='Submitting...'; const res = await automationService.setStrategy({ token:selectedToken.address, stopLossBps:Number(form.stopLossBps||0), takeProfitBps:Number(form.takeProfitBps||0), coolDown:Number(form.coolDown||300), sellPortionBps:Number(form.sellPortionBps||10000), slippageBps:Number(form.slippageBps||200), enabled:form.enabled }); txStatus='Confirmed in block '+res.blockNumber; notify.success('Strategy saved successfully!'); hydrate(); } catch(e){ const msg=e?.message||'tx failed'; txStatus='Error: '+msg; notify.error(msg.slice(0,160)); } }
  async function checkAllowance(){ if(!selectedToken?.address || !portfolioAddress) return; try { const provider = secureContractService.provider; const erc20 = new ethers.Contract(selectedToken.address, ['function allowance(address,address) view returns (uint256)'], provider); allowance = await erc20.allowance(account, portfolioAddress); } catch(e){ console.warn('allowance check failed', e.message);} }
  async function approveMax(){ if(!selectedToken?.address || !portfolioAddress) return; try { approving=true; const provider = secureContractService.provider; const signer = await provider.getSigner(); const erc20 = new ethers.Contract(selectedToken.address, ['function approve(address,uint256) returns (bool)'], signer); const max = BigInt('0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff'); const tx = await erc20.approve(portfolioAddress, max); txStatus='Approval pending...'; await tx.wait(); txStatus='Approval confirmed'; notify.success('Token approved successfully!'); checkAllowance(); } catch(e){ const msg=e?.message||'failed'; txStatus='Approval error: '+msg; notify.error(msg.slice(0,160)); } finally { approving=false; } }
  $: if(selectedToken && portfolioAddress && account){ checkAllowance(); }
</script>
<div class="p-4 bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 shadow-sm">
  <div class="flex items-start justify-between mb-2"><h2 class="text-lg font-semibold text-gray-800 dark:text-gray-100 flex items-center gap-2"><span>Automation Strategy</span>{#if selectedToken}<span class="text-sm text-gray-500 dark:text-gray-400">({selectedToken.symbol})</span>{/if}</h2>{#if strategy?.entryPrice}<div class="text-xs text-gray-500 dark:text-gray-400 flex flex-col items-end"><span class="uppercase tracking-wide">Entry</span><span>{(Number(strategy.entryPrice)/1e18).toFixed(4)}</span></div>{/if}</div>
  {#if !automationAddress}<p class="mt-2 text-sm text-amber-600">AutomationController address not configured.</p>{:else if !selectedToken}<p class="mt-2 text-sm text-gray-500">Select a token to configure a strategy.</p>{:else}
  <form class="mt-4 space-y-5" on:submit|preventDefault={save} aria-describedby="strategy-status" aria-live="off">
    <fieldset class="border border-gray-200 dark:border-gray-700 rounded-lg p-4"><legend class="px-2 text-xs font-semibold uppercase tracking-wide text-gray-500 dark:text-gray-400">Risk Triggers</legend><div class="grid grid-cols-2 gap-4"><div class="space-y-1"><label for="stopLossBps" class="flex items-center gap-1 text-xs font-medium uppercase tracking-wide text-gray-500 dark:text-gray-400">Stop Loss (bps)<span class="text-gray-400" title="Activation below entry price. 500 = 5% drop">?</span></label><input id="stopLossBps" type="number" min="0" step="1" bind:value={form.stopLossBps} placeholder="500" class="input h-8 bg-gray-50 dark:bg-gray-700" aria-describedby="stopLossHelp" /><p id="stopLossHelp" class="sr-only">Stop loss trigger in basis points below entry price</p></div><div class="space-y-1"><label for="takeProfitBps" class="flex items-center gap-1 text-xs font-medium uppercase tracking-wide text-gray-500 dark:text-gray-400">Take Profit (bps)<span class="text-gray-400" title="Trigger gain above entry. 800 = 8% rise">?</span></label><input id="takeProfitBps" type="number" min="0" step="1" bind:value={form.takeProfitBps} placeholder="800" class="input h-8 bg-gray-50 dark:bg-gray-700" aria-describedby="takeProfitHelp" /><p id="takeProfitHelp" class="sr-only">Take profit trigger in basis points above entry price</p></div></div></fieldset>
    <fieldset class="border border-gray-200 dark:border-gray-700 rounded-lg p-4"><legend class="px-2 text-xs font-semibold uppercase tracking-wide text-gray-500 dark:text-gray-400">Execution</legend><div class="grid grid-cols-3 gap-4"><div class="space-y-1"><label for="coolDown" class="flex items-center gap-1 text-xs font-medium uppercase tracking-wide text-gray-500 dark:text-gray-400">Cooldown (s)<span class="text-gray-400" title="Minimum seconds between executions">?</span></label><input id="coolDown" type="number" min="60" step="1" bind:value={form.coolDown} class="input h-8 bg-gray-50 dark:bg-gray-700" aria-describedby="coolDownHelp" /><p id="coolDownHelp" class="sr-only">Cooldown in seconds between strategy executions</p></div><div class="space-y-1"><label for="sellPortionBps" class="flex items-center gap-1 text-xs font-medium uppercase tracking-wide text-gray-500 dark:text-gray-400">Sell Portion (bps)<span class="text-gray-400" title="Portion sold when trigger hits. 10000 = full">?</span></label><input id="sellPortionBps" type="number" min="1" max="10000" step="1" bind:value={form.sellPortionBps} class="input h-8 bg-gray-50 dark:bg-gray-700" aria-describedby="sellPortionHelp" /><p class="text-[10px] text-gray-400">10000 = 100%</p><p id="sellPortionHelp" class="sr-only">Basis points of position to sell when a trigger fires</p></div><div class="space-y-1"><label for="slippageBps" class="flex items-center gap-1 text-xs font-medium uppercase tracking-wide text-gray-500 dark:text-gray-400">Slippage (bps)<span class="text-gray-400" title="Max price impact allowed. 200 = 2%">?</span></label><input id="slippageBps" type="number" min="0" max="2000" step="1" bind:value={form.slippageBps} class="input h-8 bg-gray-50 dark:bg-gray-700" aria-describedby="slippageHelp" /><p class="text-[10px] text-gray-400">200 = 2% max impact</p><p id="slippageHelp" class="sr-only">Maximum acceptable slippage in basis points</p></div></div></fieldset>
    <div class="flex flex-wrap items-center gap-4 border border-dashed border-gray-300 dark:border-gray-600 rounded-lg p-3 bg-gray-50 dark:bg-gray-800/40"><label class="flex items-center gap-2 text-sm text-gray-700 dark:text-gray-300"><input type="checkbox" bind:checked={form.enabled} class="rounded border-gray-300 text-blue-600 focus:ring-blue-500" />Enabled</label>{#if strategy?.lastExecution}<span class="text-xs text-gray-500 dark:text-gray-400">Last Exec: {new Date(strategy.lastExecution*1000).toLocaleTimeString()}</span>{/if}{#if strategy?.entryPrice && strategy.enabled}<span class="text-xs text-gray-500 dark:text-gray-400">Active @ {(Number(strategy.entryPrice)/1e18).toFixed(4)}</span>{/if}{#if allowance !== null}{#if allowance == 0n}<span class="text-xs text-amber-600">Token not approved</span>{:else}<span class="text-xs text-emerald-600">Allowance set</span>{/if}{/if}</div>
    <div class="flex items-center gap-3 pt-1"><button type="submit" class="btn btn-primary h-9 px-5" disabled={loading}>{loading ? 'Saving...' : 'Save Strategy'}</button>{#if allowance !== null}{#if allowance == 0n}<button type="button" on:click={approveMax} class="btn btn-secondary h-9 px-4" disabled={approving}>{approving ? 'Approving…' : 'Approve Token'}</button>{/if}{/if}{#if txStatus}<span id="strategy-status" role="status" aria-live="polite" class="text-xs text-gray-500 dark:text-gray-400 truncate max-w-[180px]">{txStatus}</span>{/if}</div>
  </form>
  {/if}
</div>